name=hoboNicola Library
version=1.8.0
sentence=hoboNicola keyboard and adapters for arduino
paragraph=Support AVR, SAMD21, RP2040, nRF52
author=Takeshi Higasa
maintainer=okiraku-camera.tokyo
url=https://okiraku-camera.tokyo/
category=Other
architecture=*